# for managing our services

version: "3"

services:
    app:
      build: .
      ports:
        - “8000:8000”
      env_file:
        - ./.env.prod  
      volumes: 
        - ./app:/app  
      command: > 
        bash -c “python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000”
      depends_on: 
        - db
  
    
   db:
      image: mysql
      
        
# > docker-compose build
# Create and tag image
#docker-compose run app <service> .

# docker build -t <DockerLogin>/<Docker-Image_name> .
# PS: don’t forget the “.” at the end of the above command


# Put host name "db" as per settings 